param(
    [switch]$SkipOwaspUpdate
)

$ErrorActionPreference = 'Stop'

function Write-Section($title) {
    "`n## $title`n" | Out-File -FilePath $OutputMd -Append -Encoding utf8
}

function Get-TodayString {
    return (Get-Date).ToString('yyyy-MM-dd')
}

function Ensure-TargetDir {
    if (-not (Test-Path -LiteralPath 'target')) {
        New-Item -ItemType Directory -Path 'target' | Out-Null
    }
}

function Run-Maven([string]$args, [string]$teeFile) {
    Write-Host "[audit] mvn $args"
    if ($teeFile) {
        mvn -B $args 2>&1 | Tee-Object -FilePath $teeFile | Out-Null
    } else {
        mvn -B $args | Out-Null
    }
}

function Parse-DepUpdates([string]$path) {
    $results = @()
    if (-not (Test-Path -LiteralPath $path)) { return $results }
    $lines = Get-Content -LiteralPath $path
    $inSection = $false
    foreach ($line in $lines) {
        if ($line -match 'The following dependencies.*have newer versions') { $inSection = $true; continue }
        if ($inSection -and [string]::IsNullOrWhiteSpace($line)) { continue }
        if ($inSection -and $line -match '^\s*\S') {
            # Example format:  groupId:artifactId ..................... 1.2.3 -> 1.2.4
            $m = [regex]::Match($line, '^\s*([^:]+):([^\s]+)\s+.*?([0-9A-Za-z_\.-]+)\s*->\s*([0-9A-Za-z_\.-]+)')
            if ($m.Success) {
                $group = $m.Groups[1].Value.Trim()
                $artifact = $m.Groups[2].Value.Trim()
                $current = $m.Groups[3].Value.Trim()
                $latest = $m.Groups[4].Value.Trim()
                $results += [pscustomobject]@{
                    GroupId = $group
                    ArtifactId = $artifact
                    Current = $current
                    Latest = $latest
                }
            }
        }
    }
    return $results
}

function Get-VersionParts([string]$v) {
    # Attempt to parse numeric semver-ish version; fallback to zeros
    $v2 = $v.Split('-')[0]  # drop qualifiers
    $nums = @()
    foreach ($p in $v2.Split('.')) {
        $n = 0
        if ([int]::TryParse(($p -replace '[^0-9]',''), [ref]$n)) { $nums += $n } else { $nums += 0 }
    }
    while ($nums.Count -lt 3) { $nums += 0 }
    return $nums[0..2]
}

function Classify-Update($current, $latest) {
    $c = Get-VersionParts $current
    $l = Get-VersionParts $latest
    if ($l[0] -ne $c[0]) { return 'major' }
    if ($l[1] -ne $c[1]) { return 'minor' }
    if ($l[2] -ne $c[2]) { return 'patch' }
    return 'other'
}

function Parse-DependencyCheck([string]$jsonPath) {
    $vulns = @()
    if (-not (Test-Path -LiteralPath $jsonPath)) { return $vulns }
    $json = Get-Content -LiteralPath $jsonPath -Raw | ConvertFrom-Json

    if ($null -ne $json.dependencies) {
        foreach ($dep in $json.dependencies) {
            if ($null -eq $dep.vulnerabilities) { continue }
            foreach ($v in $dep.vulnerabilities) {
                $fixed = $null
                if ($v.properties -and $v.properties.'fixed-version') { $fixed = $v.properties.'fixed-version' }
                elseif ($v.vulnerableSoftware && $v.vulnerableSoftware.Count -gt 0) {
                    # try to infer from versionEndExcluding
                    $cpe = $v.vulnerableSoftware | Where-Object { $_.versionEndExcluding }
                    if ($cpe) { $fixed = ($cpe | Select-Object -First 1).versionEndExcluding }
                }
                $vulns += [pscustomobject]@{
                    Dependency = $dep.fileName
                    PackageUrl = $dep.packageUrl
                    Id = $v.name
                    Severity = $v.severity
                    CvssScore = $v.cvssScore
                    FixedVersion = $fixed
                }
            }
        }
    } elseif ($null -ne $json.vulnerabilities) {
        foreach ($v in $json.vulnerabilities) {
            $vulns += [pscustomobject]@{
                Dependency = $null
                PackageUrl = $null
                Id = $v.name
                Severity = $v.severity
                CvssScore = $v.cvssScore
                FixedVersion = $null
            }
        }
    }
    return $vulns
}

# Main
Ensure-TargetDir
$today = Get-TodayString
$OutputMd = "dependency-audit-$today.md"
if (Test-Path -LiteralPath $OutputMd) { Remove-Item -LiteralPath $OutputMd -Force }

"# Dependency Audit ($today)" | Out-File -FilePath $OutputMd -Encoding utf8
"Generated by audit-dependencies.ps1" | Out-File -FilePath $OutputMd -Append -Encoding utf8

# Detect package managers (simple heuristics)
$managers = @()
if (Test-Path -LiteralPath 'pom.xml') { $managers += 'Maven' }
if (Test-Path -LiteralPath 'package.json') { $managers += 'npm/yarn' }
if (Test-Path -LiteralPath 'requirements.txt') { $managers += 'pip' }
if (Test-Path -LiteralPath 'src/main/resources/docker/docker-compose.yml') { $managers += 'Docker Compose (images)' }

Write-Section 'Detected package managers'
"- " + ($managers -join "`n- ") | Out-File -FilePath $OutputMd -Append -Encoding utf8

# Run versions plugin to collect updates
$depUpdatesFile = 'target/dep-updates.txt'
$pluginUpdatesFile = 'target/plugin-updates.txt'
$propUpdatesFile = 'target/property-updates.txt'
$parentUpdatesFile = 'target/parent-updates.txt'
Run-Maven 'versions:display-dependency-updates -DoutputFile=target/dep-updates.txt -DincludeTransitive=false' $depUpdatesFile
Run-Maven 'versions:display-plugin-updates -DoutputFile=target/plugin-updates.txt' $pluginUpdatesFile
Run-Maven 'versions:display-property-updates -DoutputFile=target/property-updates.txt' $propUpdatesFile
Run-Maven 'versions:display-parent-updates' $parentUpdatesFile

# Run OWASP Dependency-Check
$owaspArgs = 'org.owasp:dependency-check-maven:check -Dformat=JSON'
if ($SkipOwaspUpdate) { $owaspArgs += ' -Danalyzer.update=false -DfailOnError=false' }
Run-Maven $owaspArgs $null

# Parse reports
$depUpdates = Parse-DepUpdates $depUpdatesFile
$pluginUpdates = Parse-DepUpdates $pluginUpdatesFile
$propUpdates = Parse-DepUpdates $propUpdatesFile
$parentUpdates = Parse-DepUpdates $parentUpdatesFile

# Classify dependency updates
$patch = @(); $minor = @(); $major = @(); $other = @()
foreach ($d in $depUpdates) {
    $kind = Classify-Update $d.Current $d.Latest
    switch ($kind) {
        'patch' { $patch += $d }
        'minor' { $minor += $d }
        'major' { $major += $d }
        default { $other += $d }
    }
}

Write-Section 'Available dependency updates'
"Patch updates (safe):" | Out-File -FilePath $OutputMd -Append -Encoding utf8
foreach ($d in $patch) { "- $($d.GroupId):$($d.ArtifactId) $($d.Current) -> $($d.Latest)" | Out-File -FilePath $OutputMd -Append -Encoding utf8 }

"`nMinor updates (low risk, review release notes):" | Out-File -FilePath $OutputMd -Append -Encoding utf8
foreach ($d in $minor) { "- $($d.GroupId):$($d.ArtifactId) $($d.Current) -> $($d.Latest)" | Out-File -FilePath $OutputMd -Append -Encoding utf8 }

"`nMajor updates (potentially breaking — skipped for auto-apply):" | Out-File -FilePath $OutputMd -Append -Encoding utf8
foreach ($d in $major) { "- $($d.GroupId):$($d.ArtifactId) $($d.Current) -> $($d.Latest) (potential breaking changes)" | Out-File -FilePath $OutputMd -Append -Encoding utf8 }

if ($other.Count -gt 0) {
    "`nOther version formats (manual review):" | Out-File -FilePath $OutputMd -Append -Encoding utf8
    foreach ($d in $other) { "- $($d.GroupId):$($d.ArtifactId) $($d.Current) -> $($d.Latest)" | Out-File -FilePath $OutputMd -Append -Encoding utf8 }
}

# Plugin updates (informational)
Write-Section 'Available plugin updates (informational)'
if ($pluginUpdates.Count -eq 0) { "- None" | Out-File -FilePath $OutputMd -Append -Encoding utf8 } else {
    foreach ($d in $pluginUpdates) { "- $($d.GroupId):$($d.ArtifactId) $($d.Current) -> $($d.Latest)" | Out-File -FilePath $OutputMd -Append -Encoding utf8 }
}

# Property updates (informational)
Write-Section 'Property-managed dependency updates (informational)'
if ($propUpdates.Count -eq 0) { "- None" | Out-File -FilePath $OutputMd -Append -Encoding utf8 } else {
    foreach ($d in $propUpdates) { "- $($d.GroupId):$($d.ArtifactId) $($d.Current) -> $($d.Latest)" | Out-File -FilePath $OutputMd -Append -Encoding utf8 }
}

# Parent BOM updates
Write-Section 'Available parent BOM updates (Spring Boot)'
if ($parentUpdates.Count -eq 0) { "- None" | Out-File -FilePath $OutputMd -Append -Encoding utf8 } else {
    foreach ($d in $parentUpdates) { "- $($d.GroupId):$($d.ArtifactId) $($d.Current) -> $($d.Latest)" | Out-File -FilePath $OutputMd -Append -Encoding utf8 }
}

# Vulnerabilities
$dcJson = Get-ChildItem -Path 'target' -Filter 'dependency-check-report.json' -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
$vulns = @()
if ($dcJson) { $vulns = Parse-DependencyCheck $dcJson.FullName }

Write-Section 'Vulnerabilities (from OWASP Dependency-Check)'
if ($vulns.Count -eq 0) {
    "- None detected (or report not found)." | Out-File -FilePath $OutputMd -Append -Encoding utf8
} else {
    $sevOrder = @{ CRITICAL = 4; HIGH = 3; MEDIUM = 2; LOW = 1; INFO = 0 }
    $sorted = $vulns | Sort-Object @{ Expression = { if ($_.CvssScore) { [double]$_.CvssScore } else { $key = ([string]$_.Severity).ToUpper(); if ($sevOrder.ContainsKey($key)) { $sevOrder[$key] } else { -1 } } }; Descending = $true }
    foreach ($v in $sorted) {
        $fixed = if ($v.FixedVersion) { "; fixed in: $($v.FixedVersion)" } else { '' }
        "- $($v.Dependency) — $($v.Id) — Severity: $($v.Severity) (CVSS: $($v.CvssScore))$fixed" | Out-File -FilePath $OutputMd -Append -Encoding utf8
    }
}

# Docker images (if present)
$composePath = 'src/main/resources/docker/docker-compose.yml'
if (Test-Path -LiteralPath $composePath) {
    try {
        $yaml = Get-Content -LiteralPath $composePath -Raw
        $images = Select-String -InputObject $yaml -Pattern 'image:\s*([^\r\n]+)' -AllMatches | ForEach-Object { $_.Matches.Value.Split(':',2)[1].Trim() }
        Write-Section 'Docker images (manual update check)'
        if ($images.Count -eq 0) { "- None" | Out-File -FilePath $OutputMd -Append -Encoding utf8 } else {
            foreach ($img in $images) { "- $img (check registry for newer tags)" | Out-File -FilePath $OutputMd -Append -Encoding utf8 }
        }
    } catch {
        Write-Section 'Docker images'
        "- Failed to parse docker-compose.yml" | Out-File -FilePath $OutputMd -Append -Encoding utf8
    }
}

# Next steps
Write-Section 'Next steps'
"- I can attempt to automatically apply PATCH/MINOR updates and run tests. Do you want me to proceed?" | Out-File -FilePath $OutputMd -Append -Encoding utf8
"- Major updates are listed for review due to potential breaking changes." | Out-File -FilePath $OutputMd -Append -Encoding utf8

Write-Host "Audit complete. See $OutputMd"