server:
    port: 8085

spring:
  application:
    name: spring-domain-driver-design
  datasource:
    url: jdbc:postgresql://localhost:5432/DEMO_DB
    username: postgres
    password: toor
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/schema-DEMO_DB/changeLog-master.xml



