server:
    port: 8085
    servlet:
      context-path: /ddd

spring:
  application:
    name: spring-domain-driver-design

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/schema-DEMO_DB/changeLog-master.xml

  docker:
    compose:
      skip:
        in-tests: false
      enabled: true
      file: classpath:docker/docker-compose.yml
spring-doc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    filter: true
    operations-sorter: alpha
  api-docs.path: /v3/rest-api-docs



