version: '3.8'
services:
  db:
    image: postgres:15.5-alpine3.18
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db-postgres/docker_postgres_initialisation.sh:/docker-entrypoint-initdb.d/docker_create_multiple_databases_and_users.sh
    environment:
      - POSTGRES_MULTIPLE_DATABASES=doc_management_db,doc_management_user,documentcontent
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=doc_management_db
      - POSTGRES_USER=postgres
    networks:
      backend:
        aliases:
          - "database-test"
    container_name: spring-postgresql-db
  pgadmin:
    image: dpage/pgadmin4:8.0
    ports:
      - '8088:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: emileastih1@gmail.com
      PGADMIN_DEFAULT_PASSWORD: toor
    networks:
      backend:
        aliases:
          - "pgadmin"
    container_name: spring-pgadmin
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    ports:
      - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      backend:
        aliases:
          - "elasticsearch"
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
        resources:
            limits:
              memory: 1GB
    container_name: elasticsearch01
volumes:
  db:
    driver:
      local
  elasticsearch-data:
    driver:
      local
networks:
  backend:
    driver: bridge